board_name:
  type: select
  options:
    null: Printer Board
    CR10: CR-10
    CR10_MINI: CR-10 Mini
    CR10_S4: CR-10 S4
    CR10_S5: CR-10 S5

ezabl_points:
  type: number

ezabl_outside_grid_compensation:
  type: boolean

lcd_language:
  type: select
  options:
    en: English
    an: Aragonese
    bg: Bulgarian
    ca: Catalan
    cn: Chinese
    cz: Czech
    cz_utf8: Czech (UTF-8)
    de: German
    el: Greek
    el-gr: Greek (Greece)
    es: Spanish
    eu: Basque-Euskera
    fi: Finnish
    fr: French
    fr_utf8: French (UTF-8)
    gl: Galician
    hr: Croatian
    it: Italian
    kana: Japanese
    kana_utf8: Japanese (UTF-8)
    nl: Dutch
    pl: Polish
    pt: Portugese
    pt_utf8: Portugese (UTF-8)
    pt-br: Portugese (Brazilian)
    pt-br_utf8: Portugese (Brazilian, UTF-8)
    ru: Russian
    sk_utf8: Slovak (UTF-8)
    tr: Turkish
    uk: Ukranian
    zh_CN: Chinese (Simplified)
    zh_TW: Chinese (Taiwan)
    test: Test
